### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by suuuuperNOVA** [UBC-MDS/rainfall_prediction_g12#8]

**Comment by MaeveShi** [comment]
ReadMe file layout:

1. Overview: high level, brief description about the projects, results we've found. 
 
2.  `Compare run times on different machines within your team and summarize your observations. ome of you might not be able to do it on your laptop. It's fine if you're unable to do it. Just make sure you discuss the reasons why you might not have been able to run this on your laptop.`: 

 Discuss the run time, observation of 
- combining csv

- Load the combined CSV to memory and perform a simple EDA

on different machine.   

3. EDA:  Detailed steps and explanation of the EDA part conducted by @jasmineortega , can you send me some summary points(two or three would be enough) so that I can expand and add it into the readme?
